### ISSUE TITLE
CUDA error 'out of memory' in func 'cuda_neoscrypt::init' line 1258

### ISSUE THREAD

**Issue by mkabatek** [nicehash/NiceHashMiner-Archived#1393]
Nicehash v2.0.1.5 Beta, Windows 10

Running on GeForce GTX 1070, `CUDA 9.1.85`, `Nvidia 388.71`

`wrkr0-6 | CUDA error 'out of memory' in func 'cuda_neoscrypt::init' line 1258`

`wrkr1-7 | CUDA error DRIVER: '2' in func 'cudahelp::device_thread_init' line 168`

**Comment by Tottom** [comment]
Hi,
Same issue for me on GeForce GTX 6x 1070 and 2x 1070Ti, CUDA 9.1.85, Nvidia 388.71
CUDA error 'out of memory' in func 'cuda_neoscrypt::init' line 1258

**Comment by mkabatek** [comment]
I think it has to do with the amount of RAM in the machine. I only have 4Gb and I read somewhere else that someone added 8GB ram to their system and it fixed the issue. 

Should be fixable in software though.

**Comment by Tottom** [comment]
I do have 8GB memory on the system already... and 32GB swap. maybe i should do less on swap?

**Comment by mkabatek** [comment]
They ADDED 8Gb of memory, meaning they have 16Gb now. Here is the original thread.

https://github.com/nicehash/NiceHashMiner2/issues/173

**Comment by Tottom** [comment]
ic. Another poster says he can run 3x gtx 1070 on 8GB memory, anymore than that then he gets out of memory... so if i run 12x gtx 1070 i need 32GB RAM?

I will get 2x 8GB dimms in the new year only :( and confirm the results on my current 8 card rig.
thanks!

**Comment by Tottom** [comment]
I have changed my vmem to 96GB. Neoscrypt ran for awhile without failing... still monitoring.

**Comment by Tottom** [comment]
Hi, 

So i tried 16GB vMem and got the errors more frequently. And on 64GB vMem and had the errors maybe about 20 hours later. 

I have now upped my vMem to 98GB and i have not had any further errors in the last 24 hours. I have 6x 1070 and 2x 1070ti cards. OC 150mhz on CPU and 500mhz on memory and 65% TDP. 

I have only 8GB physical memory.

**Comment by BitcoinKid9** [comment]
Nicehash v2.0.1.5 Beta, Windows 10
Algorithm neoscrypt
cuda error out of memory in func cuda_neoscrypt::init line 1258
cuda error driver: 2 in func cudahelp::device_thread_init line 168

Same issue here.....just upgraded to Nicehash v2.0.1.6 will monitor to see if fixed running precise bench again now. I'm running 1070 ti's with 4 G Ram
I'm sure my Virtual Memory is auto....are you guys having any luck increasing it?

**Comment by Tottom** [comment]
Are you able to change your Virtual Memory at all?  how many 1070ti's 4gb are you running?

**Comment by BitcoinKid9** [comment]
Hi Tottom, I'm running:

2  ZOTAC 1070 Ti  8GB 
1  Gigabyte 1060 6GB

for a total of 3 GPU cards...my Motherboard is using 4G RAM stick and I have a 60G SSD with Windows 10.

Yes I can set the Virtual Memory manually but there is not much memory left to play with.

For now I have just disabled the Neoscrypt Algorithm on all 3 GPU's as I still have 13 other active Algorithms that are working just fine. 

Please let me know exactly what has worked to fix this Neoscrypt error for you guys?  so I can make the adjustments and turn back on the Neoscrypt Algorithm at some point. 

Thank You!

**Comment by BitcoinKid9** [comment]
Tottom, so your change to Vmem to 98GB is still working with neoscrypt with no errors?

Please advise as I will need to upgrade my ssd :)

**Comment by Tottom** [comment]
remotetech, i was running 6x 1070 and 2x 1070ti at the time when the fix for vMem helped stabilize neoscrypt. apparently a 1070 8gb card is recommended to have 10 to 15gb of vMem per card. Other guys did not seem to experience this issue and when adding more physical memory on the motherboard, 16gb instead of 8gb their issue was also then resolved. if you have 40gb vMem it might work out for you if you have enough space? Another thought, start on the vMem of 16gb then see how long it takes to give the memory error or restart excavator. then add another 8gb and see till you have a stable miner. before spending too much on another drive? I have a 180gb and can only set 128gb at this time and it also seems to just not be enough for 8x 1070 and 2x 1070ti. the excavator runs for a few minutes then restarts. I added a second disk and put the vMem on it this did not fix the issue. So i think the excavator does not like vMem on another disk or shared between disks? I am no expert on the application but anything is possible.

**Comment by Tottom** [comment]
just saw this comment from a fellow miner about Neoscrypt. Maybe it is more harsh to attempt?
from: Alex Thomas

"I had the same problem when I was mining neoscrypt and solve it like that:
format and reinstall all drv nvidia and gigabyte oc soft. and nicehash last version.
oc gigabyte soft alls gpus -20% power
open nicehash soft and make normal benchmark
now all it is working perfect , i can miner neoscrypt without errors cuda

solved
CUDA error 'out of memory' in func 'cuda_neoscrypt::init' line 1258"

**Comment by raduvultur** [comment]
4x GTX 1070 (3 ASUS, 1 MSI) on WIN10 with 4GB RAM. After I got the error above I increased the vRAM amount to 64000 MB and running now with no errors since two hours ago.

**Comment by BitcoinKid9** [comment]
Installed new drive and went with 125GB Vmem and turned back on neoscrypt and it's mining neoscrypt now with no errors for about the last 10 minutes. Never got this far before.  Thanks for all your help!

**Comment by MaxBuzzer** [comment]
I've noticed a pattern here: everyone who has posted seems to have a mixture of GPUs in their mining rig. And so do I. One GTX 1080, one GTX 1070 ti, three GTX 1070s, and one GTX 1060.

I found my issue to be optimization confusion. I'm using the NIceHash miner, and when I ran the original benchmark against my GPUs, the optimizer assumed that my three GTX 1070s were created equal. But I have 2 that overclocked higher from the factory, and one that is lower-end and therefore has a slower GPU clock. 

The optimizer picked one of the higher-end 1070s to run it's optimization against, and simply assumed that the other two were identical cards. I eventually figured out that the error was occurring when the slower GTX 1070 was hit as hard as the higher-end GTX 1070s. Which was happening within seconds of starting the miner. Sometimes it took minutes.

A possible solution, would have been to overclock all three GTX 1070 at the same speed and re-run the optimizer. But what I ended up doing is replace the the slower 1070 with a GTX 1050 Ti from a different miner. The optimizer re-ran and now all seems to be working fine.

**Comment by samywee** [comment]
I have very similar problem. I somewhat agree with HoverDrive. 

I too have mix of GPUs (1070, 1060, 1050ti, 1050 and some are factory OC'd). 

I run v2.0.1.10 (Latest as of today) - Error I get is "wrkrx-x | CUDA error 'out of memory' in func 'cuda_neoscrypt::init' line 1405" .

I have 10 GPU rig with 8GB memory. Quick look at task manager show memory is not a problem. 

Is this a bug? Should I file a bug report? When I turn off neoscrypt or remove someof my cards, this rig seems to work. Is there a gpu limit to what NiceHash can handle. Windows 10 that I use, seems to recognize all cards and use the latest drivers from NVIDIA.

**Comment by MitraTj** [comment]
I use Lab server, 8 GPUs. For running faster RCNN I have this problem.
In this case, what can I do.

Thank you!

**Comment by samywee** [comment]
MitraTJ: After reading many posts, I reverted to increase my page file to 32GB. I think for some reason, although not used, you need a large page file to run. Rule of Thumb for me seems to be have a page file size closer to 3GB or more. Some suggest to have it equal to the sum of memory of GPU cards. For me I am around 8GB Mem + 32 GB Page = 48 GB swap and now running for 2 days without error.  (3GB - 4GB may be the memory used when mining in GPU. You need that available in page file is my guess). 

Other things to try is 
1. Uder configuration -> Mining -> Device Averaging set to None
2. Disable some of the unfavorable Algos. I try to keep between 2-4 active per card. Too many profit switches hurt.

**Comment by MitraTj** [comment]
samywee: Thank you for your help. Sorry I am new in DL and using GPU. So, I should ask admin to allocate me more space of GPU, correct? Since each GPU has 12 GB of space. 
Moreover, for other things you mentioned, how can I access to configuration on the server?

Thanks!

**Comment by samywee** [comment]
Soloy : I don't run on a server. Yes sound like you need admin to change
these settings. It should be under "Virtual Memory" settings. Google it for
your version of windows.

**Comment by BitcoinKid9** [comment]
Again, I increased my onboard RAM from 4G to 8G and upgraded SSD from 60G to 250G so I could set my VM (Virtual Memory) higher to 125G. Haven't had any issues with Neoscrypt for over a month now.  I'm sure you don't need that much virtual memory allocated but I went a little overboard just to get rid of the issue.  I probably didn't need the extra stick of RAM either. It was definetly the higher VM that finally fixed the issue.

Thanks again to **Tottom** for helping me finally fix this issue. :)

**Comment by affian** [comment]
I had this issue, I changed the batch size and subdivisions from 64 & 8 to 128 & 64. Works fine but I am not sure if my model is training properly, hope this helps.
